{% set name = "faqtory" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/faqtory-{{ version }}.tar.gz
  sha256: fd8686668e946d371d8cdc4dd43ef861b4018a3cd12314aa7a0fa768805f388a

build:
  entry_points:
    - faqtory = faqtory.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - click >=8.1.3,<9.0.0
    - jinja2 >=3.1.2,<4.0.0
    - pydantic >=1.10.2,<2.0.0
    - python-frontmatter >=1.0.0,<2.0.0
    - pyyaml >=6.0,<7.0
    - rich >=12.6.0,<13.0.0
    - thefuzz >=0.19.0,<0.20.0

test:
  imports:
    - faqtory
  commands:
    - pip check
    - faqtory --help
  requires:
    - pip

about:
  home: None
  summary: Auto FAQ builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
